
#  TAHUN AKADEMIK 2026/2027 SEMESTER GASALTUGAS DATA WRANGLING & PIPELINE ANALYSIS DATA
## Nama : Muhammad Irfan Pratama
## NIM  : 25031554135
## Kelas: 2025B

In [14]:
import pandas as pd

In [15]:
baca_file = pd.read_excel("Dataset_Kesehatan_Real_Names.xlsx")

##  Penghapusan data ganda

In [16]:
baca_file.drop_duplicates()

,Kabupaten/Kota,Provinsi,Pulau,Wilayah Indonesia,Tipe Wilayah,Tahun,Prevalensi Merokok (%),AKI (per 100rb Kelahiran),AKB (per 1000 Kelahiran),Prevalensi Stunting (%),...,Prevalensi Obesitas (%),Prevalensi Hipertensi (%),Penduduk Miskin (%),Kepadatan Penduduk (Jiwa/km2),Konsumsi Alkohol (%),Pernikahan Dini (%),Cakupan BPJS/JKN (%),Indeks Kelengkapan Faskes RS (0-100),PDRB per Kapita (Juta Rp),Rasio Bed RS (per 1000 Jiwa)
0,Kabupaten Aceh Barat,Aceh,Sumatera,Barat,Kabupaten,2015,0.4424,207.29,32.79,0.3907,...,0.1510,0.3611,0.0813,422.1,0.0633,0.1361,0.5154,56.3,52.35,0.97
1,Kabupaten Aceh Barat,Aceh,Sumatera,Barat,Kabupaten,2018,0.4410,203.11,32.25,0.3841,...,0.1576,0.3554,0.0862,430.4,0.0692,0.1379,0.5959,60.6,67.55,1.03
2,Kabupaten Aceh Barat,Aceh,Sumatera,Barat,Kabupaten,2019,0.4322,183.06,30.27,0.3598,...,0.1686,0.3688,0.0726,423.3,0.0605,0.1099,0.6736,64.2,69.00,1.07
3,Kabupaten Aceh Barat,Aceh,Sumatera,Barat,Kabupaten,2021,0.4222,190.28,29.57,0.3402,...,0.1744,0.3789,0.0624,458.6,0.0543,0.0880,0.7580,67.5,71.94,1.11
4,Kabupaten Aceh Barat,Aceh,Sumatera,Barat,Kabupaten,2023,0.4260,172.12,28.15,0.3180,...,0.1812,0.3487,0.0639,458.4,0.0584,0.0817,0.8234,73.4,89.48,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2565,Kota Sorong,Papua Barat Daya,Maluku & Papua,Timur,Kota,2015,0.3634,245.50,37.07,0.4098,...,0.1063,0.3517,0.1767,2323.5,0.1504,0.1720,0.7434,59.1,87.76,1.88
2566,Kota Sorong,Papua Barat Daya,Maluku & Papua,Timur,Kota,2018,0.3494,232.15,36.56,0.4093,...,0.1193,0.3493,0.1723,2386.2,0.1513,0.1603,0.8226,63.4,104.12,1.94
2567,Kota Sorong,Papua Barat Daya,Maluku & Papua,Timur,Kota,2019,0.3383,211.92,33.21,0.3769,...,0.1201,0.3584,0.1415,2392.3,0.1290,0.1246,0.9078,66.9,103.74,1.98
2568,Kota Sorong,Papua Barat Daya,Maluku & Papua,Timur,Kota,2021,0.3350,218.19,33.54,0.3812,...,0.1250,0.3683,0.1393,2537.1,0.1326,0.1141,0.9919,71.8,123.79,2.04
2569,Kota Sorong,Papua Barat Daya,Maluku & Papua,Timur,Kota,2023,0.3368,198.48,31.17,0.3317,...,0.1232,0.3432,0.1084,2629.1,0.1085,0.0806,1.0000,73.8,117.13,2.07

## Pengecekan missing value pada data

In [17]:
tabel_cek_misingg_velue = baca_file.isna().sum()

pd.DataFrame(tabel_cek_misingg_velue)

                                      0
Kabupaten/Kota                        0
Provinsi                              0
Pulau                                 0
Wilayah Indonesia                     0
Tipe Wilayah                          0
Tahun                                 0
Prevalensi Merokok (%)                0
AKI (per 100rb Kelahiran)             0
AKB (per 1000 Kelahiran)              0
Prevalensi Stunting (%)               0
Total Fertility Rate (TFR)            0
Cakupan K4 Maternitas (%)             0
Cakupan Imunisasi Dasar (%)           0
Peserta KB Aktif (%)                  0
Anemia Ibu Hamil (%)                  0
BBLR (%)                              0
Gizi Buruk Balita (%)                 0
Persalinan oleh Nakes (%)             0
Cakupan ANC K1 (%)                    0
Prevalensi Obesitas (%)               0
Prevalensi Hipertensi (%)             0
Penduduk Miskin (%)                   0
Kepadatan Penduduk (Jiwa/km2)         0
Konsumsi Alkohol (%)                  0
Pernikahan Dini (%)                   0
Cakupan BPJS/JKN (%)                  0
Indeks Kelengkapan Faskes RS (0-100)  0
PDRB per Kapita (Juta Rp)             0
Rasio Bed RS (per 1000 Jiwa)          0

#  Tabel Dimensi Wilayah

In [18]:
df_dim_wilayah = baca_file[["Kabupaten/Kota","Provinsi","Pulau","Wilayah Indonesia"]]
df_dim_wilayah

            Kabupaten/Kota          Provinsi           Pulau Wilayah Indonesia
0     Kabupaten Aceh Barat              Aceh        Sumatera             Barat
1     Kabupaten Aceh Barat              Aceh        Sumatera             Barat
2     Kabupaten Aceh Barat              Aceh        Sumatera             Barat
3     Kabupaten Aceh Barat              Aceh        Sumatera             Barat
4     Kabupaten Aceh Barat              Aceh        Sumatera             Barat
...                    ...               ...             ...               ...
2565           Kota Sorong  Papua Barat Daya  Maluku & Papua             Timur
2566           Kota Sorong  Papua Barat Daya  Maluku & Papua             Timur
2567           Kota Sorong  Papua Barat Daya  Maluku & Papua             Timur
2568           Kota Sorong  Papua Barat Daya  Maluku & Papua             Timur
2569           Kota Sorong  Papua Barat Daya  Maluku & Papua             Timur

[2570 rows x 4 columns]

# Tabel Fakta Indikator

In [19]:
df_fakta_kesehatan = baca_file.drop(columns=["Provinsi","Pulau","Wilayah Indonesia","Tipe Wilayah"])
df_fakta_kesehatan

,Kabupaten/Kota,Tahun,Prevalensi Merokok (%),AKI (per 100rb Kelahiran),AKB (per 1000 Kelahiran),Prevalensi Stunting (%),Total Fertility Rate (TFR),Cakupan K4 Maternitas (%),Cakupan Imunisasi Dasar (%),Peserta KB Aktif (%),...,Prevalensi Obesitas (%),Prevalensi Hipertensi (%),Penduduk Miskin (%),Kepadatan Penduduk (Jiwa/km2),Konsumsi Alkohol (%),Pernikahan Dini (%),Cakupan BPJS/JKN (%),Indeks Kelengkapan Faskes RS (0-100),PDRB per Kapita (Juta Rp),Rasio Bed RS (per 1000 Jiwa)
0,Kabupaten Aceh Barat,2015,0.4424,207.29,32.79,0.3907,2.84,0.7572,0.5301,0.5251,...,0.1510,0.3611,0.0813,422.1,0.0633,0.1361,0.5154,56.3,52.35,0.97
1,Kabupaten Aceh Barat,2018,0.4410,203.11,32.25,0.3841,2.93,0.7644,0.5833,0.5813,...,0.1576,0.3554,0.0862,430.4,0.0692,0.1379,0.5959,60.6,67.55,1.03
2,Kabupaten Aceh Barat,2019,0.4322,183.06,30.27,0.3598,2.91,0.7928,0.6327,0.5767,...,0.1686,0.3688,0.0726,423.3,0.0605,0.1099,0.6736,64.2,69.00,1.07
3,Kabupaten Aceh Barat,2021,0.4222,190.28,29.57,0.3402,2.77,0.8076,0.5960,0.5588,...,0.1744,0.3789,0.0624,458.6,0.0543,0.0880,0.7580,67.5,71.94,1.11
4,Kabupaten Aceh Barat,2023,0.4260,172.12,28.15,0.3180,2.82,0.8483,0.6704,0.6035,...,0.1812,0.3487,0.0639,458.4,0.0584,0.0817,0.8234,73.4,89.48,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2565,Kota Sorong,2015,0.3634,245.50,37.07,0.4098,3.03,0.5356,0.4012,0.4282,...,0.1063,0.3517,0.1767,2323.5,0.1504,0.1720,0.7434,59.1,87.76,1.88
2566,Kota Sorong,2018,0.3494,232.15,36.56,0.4093,3.05,0.5943,0.4413,0.4736,...,0.1193,0.3493,0.1723,2386.2,0.1513,0.1603,0.8226,63.4,104.12,1.94
2567,Kota Sorong,2019,0.3383,211.92,33.21,0.3769,3.01,0.6325,0.4742,0.4599,...,0.1201,0.3584,0.1415,2392.3,0.1290,0.1246,0.9078,66.9,103.74,1.98
2568,Kota Sorong,2021,0.3350,218.19,33.54,0.3812,2.98,0.5976,0.4292,0.4607,...,0.1250,0.3683,0.1393,2537.1,0.1326,0.1141,0.9919,71.8,123.79,2.04
2569,Kota Sorong,2023,0.3368,198.48,31.17,0.3317,2.87,0.6590,0.5027,0.4944,...,0.1232,0.3432,0.1084,2629.1,0.1085,0.0806,1.0000,73.8,117.13,2.07

## Ringkasan informasi dataset

In [20]:
# shape

print(f"Shape untuk tabel df_dim_wilayah = {df_dim_wilayah.shape}")
print(f"Shape untuk tabel df_fakta_kesehatan = {df_fakta_kesehatan.shape}")

Shape untuk tabel df_dim_wilayah = (2570, 4)
Shape untuk tabel df_fakta_kesehatan = (2570, 25)

In [21]:
#types 
print(f"Types untu data frame dimensi wilayah")
print("\n")
print(df_dim_wilayah.dtypes)

print("---------"*10)

print(f"Types untu data frame fakta kesehatan")
print("\n")
print(df_fakta_kesehatan.dtypes)

Types untu data frame dimensi wilayah


Kabupaten/Kota       str
Provinsi             str
Pulau                str
Wilayah Indonesia    str
dtype: object
------------------------------------------------------------------------------------------
Types untu data frame fakta kesehatan


Kabupaten/Kota                              str
Tahun                                     int64
Prevalensi Merokok (%)                  float64
AKI (per 100rb Kelahiran)               float64
AKB (per 1000 Kelahiran)                float64
Prevalensi Stunting (%)                 float64
Total Fertility Rate (TFR)              float64
Cakupan K4 Maternitas (%)               float64
Cakupan Imunisasi Dasar (%)             float64
Peserta KB Aktif (%)                    float64
Anemia Ibu Hamil (%)                    float64
BBLR (%)                                float64
Gizi Buruk Balita (%)                   float64
Persalinan oleh Nakes (%)               float64
Cakupan ANC K1 (%)                      float64
Prevalensi Obesitas (%)                 float64
Prevalensi Hipertensi (%)               float64
Penduduk Miskin (%)                     float64
Kepadatan Penduduk (Jiwa/km2)           float64
Konsumsi Alkohol (%)                    float64
Pernikahan Dini (%)                     float64
Cakupan BPJS/JKN (%)                    float64
Indeks Kelengkapan Faskes RS (0-100)    float64
PDRB per Kapita (Juta Rp)               float64
Rasio Bed RS (per 1000 Jiwa)            float64
dtype: object

In [22]:
baca_file.columns

Index(['Kabupaten/Kota', 'Provinsi', 'Pulau', 'Wilayah Indonesia',
       'Tipe Wilayah', 'Tahun', 'Prevalensi Merokok (%)',
       'AKI (per 100rb Kelahiran)', 'AKB (per 1000 Kelahiran)',
       'Prevalensi Stunting (%)', 'Total Fertility Rate (TFR)',
       'Cakupan K4 Maternitas (%)', 'Cakupan Imunisasi Dasar (%)',
       'Peserta KB Aktif (%)', 'Anemia Ibu Hamil (%)', 'BBLR (%)',
       'Gizi Buruk Balita (%)', 'Persalinan oleh Nakes (%)',
       'Cakupan ANC K1 (%)', 'Prevalensi Obesitas (%)',
       'Prevalensi Hipertensi (%)', 'Penduduk Miskin (%)',
       'Kepadatan Penduduk (Jiwa/km2)', 'Konsumsi Alkohol (%)',
       'Pernikahan Dini (%)', 'Cakupan BPJS/JKN (%)',
       'Indeks Kelengkapan Faskes RS (0-100)', 'PDRB per Kapita (Juta Rp)',
       'Rasio Bed RS (per 1000 Jiwa)'],
      dtype='str')

In [23]:
melted = pd.melt(baca_file,id_vars=["Kabupaten/Kota","Tahun"],value_vars=['Prevalensi Merokok (%)','AKI (per 100rb Kelahiran)', 'AKB (per 1000 Kelahiran)','Prevalensi Stunting (%)', 'Total Fertility Rate (TFR)','Cakupan K4 Maternitas (%)', 'Cakupan Imunisasi Dasar (%)','Peserta KB Aktif (%)', 'Anemia Ibu Hamil (%)', 'BBLR (%)','Gizi Buruk Balita (%)', 'Persalinan oleh Nakes (%)','Cakupan ANC K1 (%)', 'Prevalensi Obesitas (%)','Prevalensi Hipertensi (%)', 'Penduduk Miskin (%)','Kepadatan Penduduk (Jiwa/km2)', 'Konsumsi Alkohol (%)','Pernikahan Dini (%)', 'Cakupan BPJS/JKN (%)','Indeks Kelengkapan Faskes RS (0-100)', 'PDRB per Kapita (Juta Rp)','Rasio Bed RS (per 1000 Jiwa)'])
melted

             Kabupaten/Kota  Tahun                      variable   value
0      Kabupaten Aceh Barat   2015        Prevalensi Merokok (%)  0.4424
1      Kabupaten Aceh Barat   2018        Prevalensi Merokok (%)  0.4410
2      Kabupaten Aceh Barat   2019        Prevalensi Merokok (%)  0.4322
3      Kabupaten Aceh Barat   2021        Prevalensi Merokok (%)  0.4222
4      Kabupaten Aceh Barat   2023        Prevalensi Merokok (%)  0.4260
...                     ...    ...                           ...     ...
59105           Kota Sorong   2015  Rasio Bed RS (per 1000 Jiwa)  1.8800
59106           Kota Sorong   2018  Rasio Bed RS (per 1000 Jiwa)  1.9400
59107           Kota Sorong   2019  Rasio Bed RS (per 1000 Jiwa)  1.9800
59108           Kota Sorong   2021  Rasio Bed RS (per 1000 Jiwa)  2.0400
59109           Kota Sorong   2023  Rasio Bed RS (per 1000 Jiwa)  2.0700

[59110 rows x 4 columns]

In [24]:
Prevalensi_Stunting = baca_file[['Kabupaten/Kota','Tahun','Prevalensi Stunting (%)',]].pivot(index="Kabupaten/Kota",columns="Tahun",values="Prevalensi Stunting (%)")
Prevalensi_Stunting

Tahun                        2015    2018    2019    2021    2023
Kabupaten/Kota
Kabupaten Aceh Barat       0.3907  0.3841  0.3598  0.3402  0.3180
Kabupaten Aceh Barat Daya  0.3693  0.3508  0.3432  0.3366  0.3022
Kabupaten Aceh Besar       0.3724  0.3348  0.3234  0.3207  0.2965
Kabupaten Aceh Jaya        0.3969  0.3575  0.3486  0.3312  0.3302
Kabupaten Aceh Selatan     0.3790  0.3443  0.3476  0.3412  0.3198
...                           ...     ...     ...     ...     ...
Kota Ternate               0.3261  0.3041  0.3002  0.2851  0.2602
Kota Tidore Kepulauan      0.3200  0.3090  0.2917  0.2882  0.2750
Kota Tomohon               0.2298  0.2216  0.1975  0.2066  0.1876
Kota Tual                  0.3821  0.3419  0.3283  0.3304  0.3109
Kota Yogyakarta            0.1815  0.1635  0.1609  0.1504  0.1437

[514 rows x 5 columns]

In [27]:
# Filter dan tampilkan seluruh kabupaten/kota pada tahun 2023 yang memenuhi dua kondisi sekaligus

filter_data  = baca_file[['Kabupaten/Kota','Tahun','Prevalensi Stunting (%)','Penduduk Miskin (%)']]
filter_data = filter_data[(filter_data['Prevalensi Stunting (%)'] > 0.30) & (filter_data['Penduduk Miskin (%)'] > 0.10)]
filter_data = filter_data[filter_data['Tahun'] == 2023 ]

filter_data

,Kabupaten/Kota,Tahun,Prevalensi Stunting (%),Penduduk Miskin (%)
1414,Kabupaten Bima,2023,0.3215,0.1438
1419,Kabupaten Dompu,2023,0.3008,0.1025
1424,Kabupaten Lombok Barat,2023,0.3292,0.1592
1429,Kabupaten Lombok Tengah,2023,0.3281,0.1432
1434,Kabupaten Lombok Timur,2023,0.3082,0.1335
...,...,...,...,...
2549,Kabupaten Raja Ampat,2023,0.3494,0.1098
2554,Kabupaten Sorong,2023,0.3774,0.1528
2559,Kabupaten Sorong Selatan,2023,0.3706,0.1557
2564,Kabupaten Tambrauw,2023,0.3579,0.1223
2569,Kota Sorong,2023,0.3317,0.1084